apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: vaultwarden
type: Opaque
data:
    {{- if .Values.smtp.username }}
  SMTP_USERNAME: {{ .Values.smtp.username | b64enc | quote }}
    {{- end }}
    {{- if .Values.smtp.password }}
  SMTP_PASSWORD: {{ .Values.smtp.password | b64enc | quote }}
    {{- end }}
    {{- if .Values.adminToken.enabled }}
  ADMIN_TOKEN: {{ .Values.adminToken.token | b64enc | quote }}
    {{- end }}
